version: '3.1'
services:
  sentinel1:
    image: harbor.insightone.cn/redis/redis:6.2.6
    container_name: redis-sentinel-1
    network_mode: "host"
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: harbor.insightone.cn/redis/redis:6.2.6
    container_name: redis-sentinel-2
    network_mode: "host"
    ports:
      - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: harbor.insightone.cn/redis/redis:6.2.6
    container_name: redis-sentinel-3
    network_mode: "host"
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf