version: '3'
services:
  redis:
    image: redis:5.0.7
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      #设置时区使用宿主机时区,防止时间少8小时
      - ./localtime:/etc/localtime:ro
      - ./data:/data
      - ./redis.conf:/redis.conf
    command: redis-server /redis.conf
    networks:
      renkaige:
        ipv4_address: 172.18.0.11
networks:
  renkaige:
    external: true
