version: '3.1'
services:
  master:
    image: harbor.insightone.cn/redis/redis:6.2.6
    container_name: redis-master
    network_mode: "host"
    ports:
      - 6379:6379

  slave1:
    image: harbor.insightone.cn/redis/redis:6.2.6
    container_name: redis-slave-1
    network_mode: "host"
    ports:
      - 6380:6380
    command: redis-server --port 6380 --slaveof node1节点ip 6379

  slave2:
    image: harbor.insightone.cn/redis/redis:6.2.6
    container_name: redis-slave-2
    network_mode: "host"
    ports:
      - 6381:6381
    command: redis-server --port 6381 --slaveof node1节点ip 6379