version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.14
    container_name: base-zookeeper
    hostname: zookeeper
    privileged: true
    restart: always
    ports:
      - 2181:2181
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./datalog:/datalog
      - ./logs:/logs
      - ./data:/data
      - ./conf:/conf
    networks:
      renkaige:
        ipv4_address: 172.18.0.21
networks:
  renkaige:
    external: true